<?php

namespace AppBundle\Repository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByProductActive()
	{
    	$query = $this->getEntityManager()
    	->createQuery(
        'SELECT p, c FROM AppBundle:Producto p
        JOIN p.categoria c
        WHERE c.status = :status'
    	)->setParameter('status', true);

    return $query->getResult();
	}
}
